### ISSUE TITLE
Provide more description

### ISSUE THREAD

**Issue by hasanbayatme** [Lorengamboa/Emulador.io#1]
It seems this is a good idea.

But has **very little description**.

I maybe can help you if you provide **more description**.

Thanks.

**Comment by Lorengamboa** [comment]
Sure, what do you suggest?

Let me know what information you want to know?

**Comment by hasanbayatme** [comment]
1. Where is it's usage?
2. How to setup? (complete installation process)
3. Give a list of supported console handheld.

Thanks.

**Comment by Lorengamboa** [comment]
Just added your three suggestions!

**Comment by hasanbayatme** [comment]
Thanks.
it is a fast issue tracking.
Nice job!
